trigger:
- main

variables: 
  solutionDir: src

pool:
  name: OnPremisesAgentPool
  vmImage: winagent

steps:
- script: dotnet build -c "Release"
  displayName: Building Solution
  workingDirectory: $(solutionDir)

- script: dotnet test -c "Release"
  displayName: Testing
  workingDirectory: $(solutionDir)
