trigger:
- main

variables: 
  solutionDir: src

pool:
  name: OnPremisesAgentPool
  vmImage: winagent

steps:
- script: cd
  displayName: what directory are we in?

- script: dir
  displayName: what files are there?

- script: msbuild
  displayName: Building Solution
  workingDirectory: $(solutionDir)
