trigger:
- main

variables: 
  solutionDir: src

pool:
  name: OnPremisesAgentPool
  vmImage: winagent

steps:
- script: dotnet build --configuration "Release"
  displayName: Building Solution
  workingDirectory: $(solutionDir)

- script: dotnet publish -o $(build.artifactStagingDirectory)
  displayName: Publish to Artifacts
  workingDirectory: $(solutionDir)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)'
    publishLocation: 'pipeline'
