trigger:
- main

variables: 
  solutionDir: src

pool:
  name: OnPremisesAgentPool
  vmImage: winagent

steps:
- script: dotnet build -c "Release"
  displayName: Building Solution
  workingDirectory: $(solutionDir)

- task: DotNetCoreCLI@2
  displayName: Running Tests
  inputs:
    command: test
    workingDirectory: $(solutionDir)
