trigger:
- main

pool:
  name: WindowsAgentPool
  vmImage: winagent

variables: 
  resourceGroupName: 'chatapp-rg'
  subscription: 'Default Service Connection'
  location: 'eastus'
  templateFile: 'main.bicep'

stages:
- stage: Provision
  jobs: 
  - job: Provision_Resources
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(subscription)
        scriptType: 'ps'
        scriptLocation: inlineScript
        useGlobalConfig: true
        inlineScript: |
          az --version
          az config set bicep.use_binary_from_path=False
          az bicep install
          az group create --name $(resourceGroupName) --location $(location)
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters location=eastus

- stage: Build
  jobs:
  - job: Build_API
    steps:
    - script: dotnet build ChatApplication.API
      displayName: Building API Project
      workingDirectory: $(solutionDir)

    - script: dotnet publish ChatApplication.API -o $(build.artifactStagingDirectory)/api
      displayName: Publishing API project build to the artifact
      workingDirectory: $(solutionDir)

    - task: PublishPipelineArtifact@1
      displayName: Publishing the API build artifact to the pipeline
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/api'
        artifact: api
        publishLocation: 'pipeline'

  - job: Build_Blazor
    steps:
    - script: dotnet build ChatApplication.Blazor
      displayName: Building Blazor Project
      workingDirectory: $(solutionDir)
    
    - script: dotnet publish ChatApplication.Blazor -o $(build.artifactStagingDirectory)/blazor
      displayName: Publishing Blazor project build to the artifact
      workingDirectory: $(solutionDir)
    
    - task: PublishPipelineArtifact@1
      displayName: Publishing the Blazor build artifact to the pipeline
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/blazor'
        artifact: blazor
        publishLocation: 'pipeline'
  
  - job: Build_Database
    steps:
    - task: MSBuild@1
      displayName: Building Database Project
      inputs:
        solution: '**/*.sqlproj'
    
    - task: CopyFiles@2
      displayName: Copying dacpac files
      inputs:
        Contents: '**/*.dacpac'
        TargetFolder: '$(build.artifactStagingDirectory)/dacpac'
        flattenFolders: true
        
    - task: PublishPipelineArtifact@1
      displayName: Publishing the database build artifact to the pipeline
      inputs:
        targetPath: '$(build.artifactStagingDirectory)/dacpac'
        artifact: dacpac
        publishLocation: 'pipeline'

- stage: Test
  jobs:
   - job: Test
     steps:
     - task: DotNetCoreCLI@2 
       displayName: Running Tests 
       inputs: 
         command: test 
         workingDirectory: $(solutionDir) 

- stage: Deploy
  jobs:
   - job: Deploy_Database
     steps:
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         artifactName: 'dacpac'
         targetPath: '$(Pipeline.Workspace)/dacpac'

     - task: SqlAzureDacpacDeployment@1
       displayName: Publishing Database project to SQL Database
       inputs:
         azureSubscription: $(subscription)
         AuthenticationType: 'server'
         ServerName: 'default-db-server.database.windows.net'
         DatabaseName: 'ChatApplication-DB'
         SqlUsername: '$(db_username)'
         SqlPassword: '$(db_password)'
         deployType: 'DacpacTask'
         DeploymentAction: 'Publish'
         DacpacFile: '$(Pipeline.Workspace)/dacpac/*.dacpac'
         IpDetectionMethod: 'AutoDetect'

   - job: Deploy_API
     steps:
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         artifactName: 'api'
         targetPath: '$(Pipeline.Workspace)/api'

     - task: ArchiveFiles@2
       inputs:
         rootFolderOrFile: '$(Pipeline.Workspace)/api/'
         includeRootFolder: false
         archiveType: 'zip'
         archiveFile: '$(Pipeline.Workspace)/PublishedApi.zip'
         replaceExistingArchive: true

     - task: AzureWebApp@1
       displayName: Publishing API project to App Service
       inputs:
        azureSubscription: $(subscription)
        appType: 'webApp'
        appName: 'ChatApplication-API'
        package: '$(Pipeline.Workspace)/PublishedApi.zip'
        deploymentMethod: 'auto'
      
   - job: Deploy_Blazor
     steps:
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         artifactName: 'blazor'
         targetPath: '$(Pipeline.Workspace)/blazor'

     - task: ArchiveFiles@2
       inputs:
         rootFolderOrFile: '$(Pipeline.Workspace)/blazor/'
         includeRootFolder: false
         archiveType: 'zip'
         archiveFile: '$(Pipeline.Workspace)/PublishedBlazor.zip'
         replaceExistingArchive: true
      
     - task: AzureWebApp@1
       displayName: Publishing Blazor project to App Service
       inputs:
        azureSubscription: $(subscription)
        appType: 'webApp'
        appName: 'ChatApplication-Blazor'
        package: '$(Pipeline.Workspace)/PublishedBlazor.zip'
        deploymentMethod: 'auto'