trigger:
- main

variables: 
  solutionDir: src

pool:
  name: WindowsAgentPool
  vmImage: winagent

steps:
- script: dotnet build
  displayName: Building Solution
  workingDirectory: $(solutionDir)

- task: DotNetCoreCLI@2
  displayName: Running Tests
  inputs:
    command: test
    workingDirectory: $(solutionDir)
