trigger:
- main

variables: 
  solutionDir: src

pool:
  name: OnPremisesAgentPool
  vmImage: winagent

steps:
- script: dotnet build --configuration "Release"
  displayName: Building Solution
  workingDirectory: $(solutionDir)

- script: dotnet test
  displayName: Testing
