name: BicepTemplateDeployment

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

env:
  subscriptionId: c95fc188-feb0-42fb-86ac-27763f04107a

jobs:
  bicepAzCliDeploy:
    name: Bicep AZ CLI Deploy Job
    runs-on: ubuntu-latest

    env:
      rg_name: rg-bicep-test
      location: eastus
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment sub create \
            --name ${{ env.rg_name }} \
            --location ${{ env.location }} \
            --template-file ./bicep-templates/resourcegroup.bicep \
            --parameters \
            resourceGroupName=${{ env.rg_name }} \
            location=${{ env.location }} \

      - name: Deploy Virtual Network
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create \
            --resource-group ${{ env.rg_name }}
            --template-file ./bicep-templates/virtualnetwork.bicep \
            --parameters \
            vNetPrefix=bicepazclitest
            location=${{ env.location }}

  bicepArmDeploy:
    name: Bicep ARM Deploy Job
    runs-on: ubuntu-latest

    env:
      rg_name: rg-bicep-test
      location: eastus
    
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Resource Group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: c95fc188-feb0-42fb-86ac-27763f04107a
          region: ${{ env.location }}
          template: ./bicep-templates/resourcegroup.bicep
          deploymentName: ${{ env.rg_name }}
          parameters:
            resourceGroupName=${{ env.rg_name }}
            location=${{ env.location }}

      - name: Deploy Virtual Network
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.rg_name }}
          subscriptionId: c95fc188-feb0-42fb-86ac-27763f04107a
          template: ./bicep-templates/resourcegroup.bicep
          parameters:
            vNetPrefix=bicepamrtest
            location=${{ env.location }}
